// v2 anatomical brain: shared constants for the shell, region labels and camera.
// Mirrors backend/brain_layout.py (lateral view: x = front(+)/back(-), y = up, z = right/left).
import { Region } from "../types";

/** Visual centre of the brain; camera target for HOME. */
export const BRAIN_CENTER: [number, number, number] = [-0.3, 0.2, 0];

/** Height of the magenta query neuron in INPUT (backend uses the same value). */
export const QUERY_SPAWN_Y = 9.5;

/** Static mesh generated by `python brain_layout.py --shell ...` (served from /public). */
export const BRAIN_SHELL_URL = "/brain_shell.json";

export const SHELL_STYLE = {
  color: "#7fb4ff",
  rimColor: "#b9d4ff",
  opacity: 0.05,      // face-on transparency
  rimOpacity: 0.32,   // fresnel edge
  rimPower: 2.6,
};

/** Where each region label floats (just outside the surface, readable from the side). */
export const REGION_LABELS: { region: Region; text: string; position: [number, number, number] }[] = [
  { region: "frontal", text: "FRONTAL", position: [3.6, 3.9, 0.6] },
  { region: "parietal", text: "PARIETAL", position: [-0.6, 4.6, 0.6] },
  { region: "occipital", text: "OCCIPITAL", position: [-5.2, 2.8, 0.6] },
  { region: "temporal", text: "TEMPORAL", position: [2.2, -3.4, 2.6] },
  { region: "hippocampus", text: "HIPOCAMPO", position: [-0.4, -1.0, 3.3] },
  { region: "cerebellum", text: "CEREBELO", position: [-3.8, -5.0, 1.2] },
];
